#!/bin/bash

JOB_ID="$1"

STATE=$(sacct --format state --parsable2 --jobs "${JOB_ID}" | tail -n1)

case "${STATE}" in
	*RUNNING*|*PENDING*|*SUSPENDED*|*COMPLETING*|*CONFIGURING* )
		echo running
                exit 0
		;;
	*COMPLETED* )
		echo success
                exit 0
		;;
	*BOOT_FAIL*|*CANCELLED*|*FAILED*|*NODE_FAIL*|*PREEMPTED*|*SPECIAL_EXIT*|*STOPPED*|*TIMEOUT* )
		echo failed
		exit 0
		;;
	"" )
		# Slurm knows nothing about the provided Job_ID
		echo failed
		exit 0
		;;
	* )
		# Assume anything else returned by Slurm is indicative of the job still running
		echo running
		exit 0
		;;
esac

exit 1
